[workspace]
members = ["projects/*"]
default-members = [
    "projects/wolfram-ast",
    "projects/wolfram-parser",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
